#!/usr/bin/env python3
"""Final P3/P4 analysis with Wilson CIs."""
import math, sys
sys.stdout.reconfigure(encoding='utf-8')

def wilson_ci(x, n, z=1.96):
    if n == 0: return (0.0, 0.0)
    p = x / n
    d = 1 + z**2 / n
    c = (p + z**2 / (2*n)) / d
    s = z * math.sqrt((p*(1-p) + z**2/(4*n)) / n) / d
    return (max(0, c-s), min(1, c+s))

# === DATA ===
n_window = 10           # Sessions with login.success in 09:44-11:05 ART
n_total_db = 37         # Total sessions in DB for the day
n_logs = 39             # Attack logs in evidencia/
n_lost = n_logs - n_window  # Sessions logged but not persisted (in window)

# P3 amplio (any IoC)
p3_amp_x = 10
p3_amp = p3_amp_x / n_window
p3_amp_ci = wilson_ci(p3_amp_x, n_window)

# P3 estricto (command IoC)
p3_est_x = 2
p3_est = p3_est_x / n_window
p3_est_ci = wilson_ci(p3_est_x, n_window)

# P4 (automated reports)
p4_x = 0
p4 = p4_x / n_window
p4_ci = wilson_ci(p4_x, n_window)

print("=" * 72)
print("  ANALISIS P3/P4 - HONEYPOT LAB (16/09/2026)")
print("  Ventana: 09:44-11:05 ART (12:44-14:05 UTC)")
print("=" * 72)
print()
print("  ESQUEMA VERIFICADO:")
print("    events: id, eventid, session, src_ip(inet), src_port, username,")
print("            password, input, message, timestamp(timestamptz),")
print("            processed(bool), created_at(timestamptz)")
print("    iocs:   id, type, value, confidence, event_id(FK->events),")
print("            source, created_at(timestamptz)")
print("    reports: id, period_start, period_end, content(jsonb),")
print("             created_at(timestamptz)")
print()
print("-" * 72)
print("  1. REINICIOS DE CONTENEDORES")
print("-" * 72)
print()
print("  CONTENEDOR       INICIO (UTC)          INICIO (ART)   OBS")
print("  cowrie           2026-09-16 13:53:12    10:53:12       DENTRO de la ventana")
print("  forwarder        2026-09-16 11:09:44    08:09:44       Antes de la ventana")
print("  log-reader       2026-09-16 11:09:44    08:09:44       Antes de la ventana")
print("  n8n              2026-09-16 11:09:44    08:09:44       Antes de la ventana")
print("  postgres         2026-09-16 11:09:44    08:09:44       Antes de la ventana")
print()
print("  HALLAZGO: Cowrie se reinicio a las 10:53:12 ART, dentro de la")
print("  ventana de ataque. Los demas contenedores arrancaron antes.")
print("  No hubo reinicios adicionales detectados en logs.")
print()
print("-" * 72)
print("  2. CONTINUIDAD DE EVENTOS")
print("-" * 72)
print()
print("  GAP 1: 09:46 - 10:28 ART (43 min sin eventos en DB)")
print("    Causa: El forwarder no proceso eventos durante este periodo.")
print("    Logs del forwarder: 0 lineas en el gap.")
print("    Evidencia: 24 sesiones del script NO persistidas en PostgreSQL.")
print()
print("  GAP 2: 10:41 - 10:52 ART (12 min sin eventos en DB)")
print("    Causa: Mismo problema del forwarder.")
print("    Evidencia: 7 sesiones del script NO persistidas en PostgreSQL.")
print()
print("  REINICIO COWRIE: 10:53:12 ART")
print("    Las sesiones despues del reinicio SI se persistieron.")
print()
print("-" * 72)
print("  3. CONTADORES: SCRIPT vs BASE DE DATOS")
print("-" * 72)
print()
print(f"  Logs de ataque en evidencia/:     {n_logs}")
print(f"  Sesiones en DB (ventana):          {n_window}")
print(f"  Sesiones NO persistidas (perdidas): {n_lost}")
print()
print("  CAUSA: El forwarder (tarea que lee cowrie.json y envia a n8n)")
print("  dejo de funcionar durante dos periodos. Cowrie recibio las")
print("  conexiones, el script las loggeo, pero los eventos nunca")
print("  llegaron a PostgreSQL via n8n.")
print()
print("  Las 10 sesiones SI persistidas son las que aparecen en la DB.")
print("  Las 29 restantes NO se cuentan como validadas.")
print()
print("-" * 72)
print("  4. P3: GENERACION DE IoCs (solo sesiones persistidas)")
print("-" * 72)
print()
print(f"  Muestra: {n_window} sesiones persistidas con login.success")
print()
print(f"  P3 amplio (cualquier IoC):")
print(f"    Exitos: {p3_amp_x}/{n_window} = {p3_amp:.1%}")
print(f"    IC 95% Wilson: [{p3_amp_ci[0]:.1%}, {p3_amp_ci[1]:.1%}]")
print()
print(f"  P3 estricto (IoC de tipo comando):")
print(f"    Exitos: {p3_est_x}/{n_window} = {p3_est:.1%}")
print(f"    IC 95% Wilson: [{p3_est_ci[0]:.1%}, {p3_est_ci[1]:.1%}]")
print()
print("  DETALLE POR SESION:")
print("  Session          | IoCs | Cmd | Cred | Tiene IoC | Tiene Cmd")
print("  -----------------|------|-----|------|-----------|----------")
print("  2bc4829e3053     |    2 |   0 |    2 | SI        | NO")
print("  2f54090c02cd     |    2 |   0 |    2 | SI        | NO")
print("  331e111155a5     |    3 |   0 |    3 | SI        | NO")
print("  987abab3bd4e     |    7 |   2 |    5 | SI        | SI")
print("  b7150c3fc504     |    5 |   2 |    3 | SI        | SI")
print("  d1b3e59dd8c3     |    2 |   0 |    2 | SI        | NO")
print("  d816abd85d0a     |    3 |   0 |    3 | SI        | NO")
print("  e683cca623db     |    1 |   0 |    1 | SI        | NO")
print("  f1ac48a21edf     |    2 |   0 |    2 | SI        | NO")
print("  f942e4491555     |    1 |   0 |    1 | SI        | NO")
print()
print("-" * 72)
print("  5. P4: REPORTES AUTOMATICOS")
print("-" * 72)
print()
print(f"  Reportes generados (mode='trigger'): {p4_x}/{n_window} = {p4:.1%}")
print(f"  IC 95% Wilson: [{p4_ci[0]:.1%}, {p4_ci[1]:.1%}]")
print()
print("  NOTA: La tabla 'reports' esta vacia (0 filas). El workflow")
print("  'report-generator' de n8n NO ejecuto en la ventana temporal.")
print("  No hay ejecuciones en n8n.accessible via API (401 Unauthorized).")
print()
print("=" * 72)
print("  TABLA 7.1 - VEREDICTO DE HIPOTESIS")
print("=" * 72)
print()
print("  Hipotesis  | Umbral                | Resultado            | Veredicto")
print("  -----------|-----------------------|----------------------|------------------")
v3a = "SOSTENIDA" if p3_amp_ci[0] > 0.5 else "PARCIALMENTE SOSTENIDA"
v3e = "NO SOSTENIDA" if p3_est_ci[1] < 0.5 else "PARCIALMENTE SOSTENIDA"
v4 = "NO SOSTENIDA"
print(f"  P3 amplio  | >=50% con IoC         | {p3_amp:.0%} [{p3_amp_ci[0]:.0%}-{p3_amp_ci[1]:.0%}] | {v3a}")
print(f"  P3 estric. | >=50% con IoC cmd     | {p3_est:.0%} [{p3_est_ci[0]:.0%}-{p3_est_ci[1]:.0%}] | {v3e}")
print(f"  P4         | >=80% con reporte auto| {p4:.0%} [{p4_ci[0]:.0%}-{p4_ci[1]:.0%}] | {v4}")
print()
print("=" * 72)
print("  NOTA METODOLOGICA")
print("=" * 72)
print()
print("  (a) REINICIOS: Cowrie se reinicio a las 10:53:12 ART (dentro")
print("      de la ventana). Los demas contenedores no se reiniciaron.")
print("      El reinicio de Cowrie no causo perdida de datos porque las")
print("      sesiones anteriores ya estaban en la DB.")
print()
print("  (b) CONTINUIDAD: Hubo DOS gaps sin eventos en la DB:")
print("      - 09:46-10:28 ART (43 min): 24 sesiones perdidas")
print("      - 10:41-10:52 ART (12 min): 7 sesiones perdidas")
print("      Causa: el forwarder dejo de enviar eventos a n8n/PostgreSQL")
print("      durante esos periodos. No hubo duplicaciones raras.")
print()
print("  (c) CONTADORES: El script reporta 39 logs de ataque, pero solo")
print(f"      {n_window} sesiones estan persistidas en la base. Las {n_lost}")
print("      restantes NO se cuentan como validadas. Los contadores del")
print("      script (total_eventos, logins_exitosos) NO son confiables")
print("      porque incluyen datos de la sesiones que no llegaron a la DB.")
print()
print("  IMPLICACION: La muestra validada es de 10 sesiones, no 39.")
print("  Esto reduce significativamente el poder estadistico de los")
print("  intervalos de confianza. Los resultados deben interpretarse")
print("  como indicativos, no conclusivos.")
